services:
  consulta-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pawpaws-consulta-api
    ports:
      - "8082:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      Cassandra__ContactPoint: cassandra
      Cassandra__Port: 9042
      Cassandra__Keyspace: papaws_consulta
      Services__AnimalesBaseUrl: http://animales-api:8080
    depends_on:
      - cassandra
    networks:
      - pawpaws-consulta-net

  cassandra:
    image: cassandra:4.1
    container_name: pawpaws-consulta-cassandra
    environment:
      CASSANDRA_CLUSTER_NAME: pawpaws-consulta
    ports:
      - "9043:9042"
    volumes:
      - pawpaws-consulta-cassandra-data:/var/lib/cassandra
    networks:
      - pawpaws-consulta-net

volumes:
  pawpaws-consulta-cassandra-data:

networks:
  pawpaws-consulta-net:
    driver: bridge
